name: ng169
description: ervery LoveNovel by no advertion.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 10.3.0+34
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  font_awesome_flutter: any
  shared_preferences: any
  #sql
  sqflite: any
  #http
  dio: any
  #二维码 
  #barcode_scan: ^0.0.3
  image_picker: any
  # image_picker: 0.6.0
  # 报错需要移除插件crop.dart中第63行的“, Drag”
  crop_your_image : any    
  # image_cropper: any
  flutter_easyrefresh: any
  flutter_spinkit: any
  web_socket_channel: any
  cached_network_image: 3.3.1
  # banner滑动
  # flutter_card_swiper: any 
  #权限
  permission_handler: any
  #工具类库
  # url_launcher: 2.8.0
  # dart_json_mapper: anynn
  # 打开app工具
  receive_intent  : any
  
  url_launcher: any
  # 监听浏览器唤醒路劲
  uni_links: any
  # flutter_webview_plugin: any
  webview_flutter: any
   
  #app缓存
  path_provider: any
  #app信息
  package_info: any
  #打开文件
  open_file: any
  # install_plugin_v2  : any
  connectivity: any
  #设备信息
  #device_info : 0.4.1
  # dio:any
  # battery: any 
  battery_info: any
  #intl: ^0.15.8
  device_info_plus: any
  device_apps: any
  carousel_slider: any
  # 富文本
  css_text: ^3.0.0
  #通知栏
  flutter_local_notifications: 17.1.0
  draggable_scrollbar: any
  #支付插件已集成到项目
  flutter_screen_wake: any
  crypto: any
  share: any
  #谷歌苹果内购
  in_app_purchase: any
  #谷歌登入
  # google_sign_in: ^6.2.1
  # flutter_facebook_auth: any
  # facebook_login: any

  third_party_login: ^1.0.14

  get_time_ago: any
  # firebase_core: any
  # firebase_analytics: any
  # firebase_auth: any
  # flutter_all_social_login : any
  # firebase_crashlytics: ^0.1.3
  # firebase_messaging: ^6.0.9
  #   
  # google_sign_in: any
  # flutter_facebook_login: any
  # flutter_datetime_picker: any
  # facebook广告
  # facebook_audience_network: 0.6.2
  #设备idfa ，广告唯一编码
  # advertising_id: ^0.9.2
  # 新义互联
  # flutter_xy_plugin: any
  # 腾讯广告 谷歌不允许适用腾讯组件
  # tencent_ad: ^1.0.2+2
  # 富文本输入框
  #图片预览
  photo_view: any
  # 文件选择
  file_picker: any
  
  # firebase_admob: any
  # 谷歌市场评论
  # in_app_review : any
  # app_review :  any
  extended_text_field: 13.0.1 
    # path: kz/extended_text_field-13.0.1      
dev_dependencies:
  flutter_test:
    sdk: flutter
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/
      - assets/lang/
      - assets/mock/
      - assets/images/
      - assets/images/gif/
      - assets/images/cy/
      - assets/images/emjo/
      - assets/images/loading/
      - assets/images/mock/
      - assets/images/mock/th/
      - assets/images/mock/id/
      - assets/images/mock/ms/
      - assets/images/mock/vi/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LoveCraft
      fonts:
        - asset: assets/font/Love-Craft-Italic-3.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

